FROM python:3.11-slim

ARG PG_HOST
ARG PG_PORT
ARG PG_PASSWORD
ARG PG_USER
ARG PG_DATABASE
ARG PG_PORT
ARG GROQ_API_KEY
ARG AUTH_API_KEY

ENV PG_HOST=${PG_HOST}
ENV PG_PORT=${PG_PORT}
ENV PG_PASSWORD=${PG_PASSWORD}
ENV PG_USER=${PG_USER}
ENV PG_DATABASE=${PG_DATABASE}
ENV PG_PORT=${PG_PORT}
ENV GROQ_API_KEY=${GROQ_API_KEY}
ENV AUTH_API_KEY=${AUTH_API_KEY}

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]