FROM python:3.11-slim

ARG PG_HOST
ARG PG_PORT
ARG PG_PASSWORD
ARG PG_USER
ARG PG_DATABASE
ARG OPENAI_API_KEY
ARG JWT_SECRET
ARG JWT_ACCESS_TOKEN_EXPIRE_MINUTES
ARG PASSWORD_HASH_ITERATIONS
ARG LLM_MODEL
ARG MAX_CHAT_TOKENS
ARG DB_POOL_SIZE
ARG MILVUS_HOST
ARG MILVUS_PORT
ARG MILVUS_COLLECTION_NAME
ARG MILVUS_TOP_K
ARG MILVUS_TOKEN
ARG MINIO_ENDPOINT
ARG MINIO_ACCESS_KEY
ARG MINIO_SECRET_KEY
ARG MINIO_BUCKET
ARG MINIO_SECURE
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_DB
ARG ARQ_MAX_JOBS
ARG ARQ_JOB_TIMEOUT

ENV PG_HOST=${PG_HOST}
ENV PG_PORT=${PG_PORT}
ENV PG_PASSWORD=${PG_PASSWORD}
ENV PG_USER=${PG_USER}
ENV PG_DATABASE=${PG_DATABASE}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_ACCESS_TOKEN_EXPIRE_MINUTES=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
ENV PASSWORD_HASH_ITERATIONS=${PASSWORD_HASH_ITERATIONS}
ENV LLM_MODEL=${LLM_MODEL}
ENV MAX_CHAT_TOKENS=${MAX_CHAT_TOKENS}
ENV DB_POOL_SIZE=${DB_POOL_SIZE}
ENV MILVUS_HOST=${MILVUS_HOST}
ENV MILVUS_PORT=${MILVUS_PORT}
ENV MILVUS_COLLECTION_NAME=${MILVUS_COLLECTION_NAME}
ENV MILVUS_TOP_K=${MILVUS_TOP_K}
ENV MILVUS_TOKEN=${MILVUS_TOKEN}
ENV MINIO_ENDPOINT=${MINIO_ENDPOINT}
ENV MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
ENV MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
ENV MINIO_BUCKET=${MINIO_BUCKET}
ENV MINIO_SECURE=${MINIO_SECURE}
ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PORT=${REDIS_PORT}
ENV REDIS_DB=${REDIS_DB}
ENV ARQ_MAX_JOBS=${ARQ_MAX_JOBS}
ENV ARQ_JOB_TIMEOUT=${ARQ_JOB_TIMEOUT}

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
